### ISSUE TITLE
Unable to add folder to ignore folder list

### ISSUE THREAD

**Issue by ajnasaboobacker** [HardcodeCoder/PulseMusic#105]
I was trying to add my call record folder to be ignored from showing up in the library. When clocked it says "No media folder found in storage".
Hope you can fix this up.

Attached a screenshot for reference. 
![Screenshot_20210405_113800_com hardcodecoder pulsemusic](https://user-images.githubusercontent.com/47502431/113543165-6d6f2180-9603-11eb-9ee4-8d9ad8830e5c.jpg)

**Comment by HardcodeCoder** [comment]
Try restarting your device and check again. Also please check for any logs in `/Android/data/com.hardcodecoder.pulsemusic/files/`

**Comment by ajnasaboobacker** [comment]
I tried restarting my device and even tried to clear the cache and data of the app.. Still no luck

Logs is as below



*********** BEGINNING OF CRASH ***********
2021-04-05_11:30:17
c.d.a.u.y at: executeAsync(): callable
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at c.d.a.u.i.compare(:2)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:208)
	at c.d.a.u.y.call(:1)
	at c.d.a.i.run(:1)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)


*********** BEGINNING OF CRASH ***********
2021-04-05_11:36:47
c.d.a.u.y at: executeAsync(): callable
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at c.d.a.u.i.compare(:2)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:208)
	at c.d.a.u.y.call(:1)
	at c.d.a.i.run(:1)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)


*********** BEGINNING OF CRASH ***********
2021-04-05_11:49:36
c.d.a.u.y at: executeAsync(): callable
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at c.d.a.u.i.compare(:2)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:208)
	at c.d.a.u.y.call(:1)
	at c.d.a.i.run(:1)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)


*********** BEGINNING OF CRASH ***********
2021-04-05_11:49:47
c.d.a.u.y at: executeAsync(): callable
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at c.d.a.u.i.compare(:2)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:208)
	at c.d.a.u.y.call(:1)
	at c.d.a.i.run(:1)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)


*********** BEGINNING OF CRASH ***********
2021-04-05_11:50:13
c.d.a.u.y at: executeAsync(): callable
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at c.d.a.u.i.compare(:2)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:208)
	at c.d.a.u.y.call(:1)
	at c.d.a.i.run(:1)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)


*********** BEGINNING OF CRASH ***********
2021-04-05_11:50:28
c.d.a.u.y at: executeAsync(): callable
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at c.d.a.u.i.compare(:2)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:208)
	at c.d.a.u.y.call(:1)
	at c.d.a.i.run(:1)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)


*********** BEGINNING OF CRASH ***********
2021-04-05_11:50:40
c.d.a.u.y at: executeAsync(): callable
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at c.d.a.u.i.compare(:2)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:208)
	at c.d.a.u.y.call(:1)
	at c.d.a.i.run(:1)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)


*********** BEGINNING OF CRASH ***********
2021-04-05_11:50:43
c.d.a.u.y at: executeAsync(): callable
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at c.d.a.u.i.compare(:2)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:208)
	at c.d.a.u.y.call(:1)
	at c.d.a.i.run(:1)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)


*********** BEGINNING OF CRASH ***********
2021-04-06_12:44:46
c.d.a.u.y at: executeAsync(): callable
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at c.d.a.u.i.compare(:2)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:208)
	at c.d.a.u.y.call(:1)
	at c.d.a.i.run(:1)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)


*********** BEGINNING OF CRASH ***********
2021-04-06_12:44:49
c.d.a.u.y at: executeAsync(): callable
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at c.d.a.u.i.compare(:2)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:221)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:208)
	at c.d.a.u.y.call(:1)
	at c.d.a.i.run(:1)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by ajnasaboobacker** [comment]
Is this fixed, if yes, how can i update my app?

**Comment by HardcodeCoder** [comment]
This fix will be included in the next release. If you are using f-droid, you will receive the update automatically.
